gspann-content/eds-universal-editor

- blocks/tabs/_tabs.json
- blocks/tabs/tabs.css
- blocks/tabs/tabs.js
Test URLs:
- Before: https://feature-tab--eds-universal-editor--gspann-content.aem.page/
- After: https://feature-tab--eds-universal-editor--gspann-content.aem.live/
> initial commit

- blocks/hero-banner/_hero-banner.json
- blocks/hero-banner/hero-banner.js
- component-definition.json
- component-filters.json
- component-models.json
- styles/tailwind.css
Test URLs:
- After: https://hero-banner--eds-universal-editor--gspann-content.aem.live/
> Hero banner

- blocks/tabs/_tabs.json
- blocks/tabs/tabs.css
- blocks/tabs/tabs.js
Test URLs:
Before: https://feature-tab--eds-doc-editor--gspann-content.aem.page/
After: https://main--eds-doc-editor--gspann-content.aem.live/
> tabs like cards

- blocks/breadcrumb/_breadcrumb.json
- blocks/breadcrumb/breadcrumb.css
- blocks/breadcrumb/breadcrumb.js
- blocks/header-bar/header-bar.css
- component-definition.json
- component-filters.json
- component-models.json
- scripts/scripts.js
Test URLs:
- After: https://breadcrumbFinal--eds-universal-editor--gspann-content.aem.live/
> Breadcrumb Block 

- blocks/hero-banner/hero-banner.js
Test URLs:
- Before: https://herobanner-picture--eds-universal-editor--gspann-content.aem.live/
- After: https://main--eds-universal-editor--gspann-content.aem.live/
> replaced img to picture tag

- blocks/tabs/tabs.js
Test URLs:
- After: https://feature-tabs-ue--eds-universal-editor--gspann-content.aem.live/
> Tabs block related js

- blocks/header-bar/header-bar.css
Test URLs:
- After: https://header-bug-fix--eds-universal-editor--gspann-content.aem.live/
> Added Css changes to fix header misalignment

- blocks/menu/menu.css
Test URLs:
- After: https://tailwind-css-refactoring--eds-universal-editor--gspann-content.aem.live/
> Added required class changes to remove tailwind

- blocks/page-title/page-title.css
- blocks/page-title/page-title.js
- component-definition.json
Test URLs:
- After: https://feature-page-title--eds-universal-editor--gspann-content.aem.live/
> page-title block

- blocks/breadcrumb/breadcrumb.css
- blocks/header-bar/header-bar.css
Test URLs:
- After: https://header-bug-fix--eds-universal-editor--gspann-content.aem.live/
> Added Css changes for Header Misalignment issues

- blocks/horizontal-vertical/horizontal-vertical.css
Test URLs:
- After: https://revert-fonts--eds-universal-editor--gspann-content.aem.live/
> Horizontal-vertical block css changes

- blocks/page-title/page-title.css
Test URLs:
- After: https://header-bug-fix--eds-universal-editor--gspann-content.aem.live/
> Added CSS bug fix for home page

- blocks/media-grid/_media-grid.json
- blocks/media-grid/media-grid.js
- component-definition.json
- component-filters.json
- component-models.json
Fix #
Test URLs:
- After: https://feature-media-grid--eds-universal-editor--gspann-content.aem.live/
> FM-31 | Media grid block

- blocks/split-image-text/split-image-text.js
Test URLs:
- After: https://feature-media-grid--eds-universal-editor--gspann-content.aem.live/
> Split image text changes

- blocks/tabs/tabs.css
- blocks/tabs/tabs.js
- styles/styles.css
Test URLs:
- After: https://feature-tabs-fix--eds-universal-editor--gspann-content.aem.live/
> Tabs block changes

- blocks/hero-banner/hero-banner.css
Test URLs:
- After: https://bug-fix-img-text--eds-universal-editor--gspann-content.aem.live/
> Added css fix for hero banner

- blocks/sciex-columns/_sciex-columns.json
- blocks/sciex-columns/sciex-columns.css
- blocks/sciex-columns/sciex-columns.js
- component-definition.json
- component-filters.json
- component-models.json
Test URLs:
- After: https://sciexColumns--eds-universal-editor--gspann-content.aem.live/
> Sciex columns

- blocks/page-subnav/page-subnav.json
- component-models.json
Test URLs:
- After: https://feature-page-subnavA--eds-universal-editor--gspann-content.aem.live/
> modified page-subnav models

- blocks/page-subnav/page-subnav.css
- blocks/page-subnav/page-subnav.js
- blocks/page-subnav/page-subnav.json
- component-filters.json
- component-models.json
Test URLs:
- After: https://feature-page-subnavA--eds-universal-editor--gspann-content.aem.live/
> Feature page subnav a

- blocks/testpage/testpage.css
- blocks/testpage/testpage.js
- component-models.json
Test URLs:
- After: https://feature-testblock--eds-universal-editor--gspann-content.aem.page/
> add changes

- blocks/hero-banner/_hero-banner.json
- blocks/hero-banner/hero-banner.css
- blocks/toggle/_toggle.json
- component-definition.json
- component-models.json
Test URLs:
- After: https://feature-toggle--eds-universal-editor--gspann-content.aem.page/
> Feature toggle

- blocks/toggle/_toggle.json
- component-models.json
Test URLs:
- After: https://feature-pagetuggle--eds-universal-editor--gspann-content.aem.page/
> modified json file

- blocks/toggle/_toggle.json
- component-models.json
Test URLs:
- After: https://feature-pagetuggle--eds-universal-editor--gspann-content.aem.live/
> modified the json

- blocks/tab-filters/_tab-filters.json
- component-definition.json
- component-filters.json
- component-models.json
- models/_section.json
Test URLs:
- After: https://feature-tab-filters--eds-universal-editor--gspann-content.aem.page/
>  add new block

- blocks/items-cart/_items-cart.json
- blocks/pagging/pagging.css
- blocks/pagging/pagging.js
- blocks/tab-filters/tab-filters.css
- blocks/tab-filters/tab-filters.js
- blocks/toggle/toggle.css
- blocks/toggle/toggle.js
- component-definition.json
- component-filters.json
- component-models.json
- icons/left-icon.svg
- icons/right-icon.svg
- models/_section.json
- reshot-icon-right-arrow-UCA8NGYZDJ.svg
- styles/global.css
Test URLs:
- After: https://feature-items-cart--eds-universal-editor--gspann-content.aem.page/
> add new block items-cards

- blocks/items-cart/_items-cart.json
- component-models.json
Test URLs:
- After: https://feature-modified-content--eds-universal-editor--gspann-content.aem.page/
> feature-modified-content

- blocks/items-cart/_items-cart.json
- component-models.json
Test URLs:
- After: https://feature-sidebar--eds-universal-editor--gspann-content.aem.page/
> feature-sidebar
